# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spotify.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rspotify.proto\"\xcd\x01\n\x07Spotify\x12\x10\n\x08track_id\x18\x01 \x01(\t\x12\x12\n\ntrack_name\x18\x02 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x03 \x01(\t\x12\r\n\x05genre\x18\x04 \x01(\t\x12\x12\n\npopularity\x18\x05 \x01(\x05\x12\x10\n\x08\x64uration\x18\x06 \x01(\x05\x12\r\n\x05tempo\x18\x07 \x01(\x05\x12\x10\n\x08\x65xplicit\x18\x08 \x01(\x08\x12\x13\n\x0binteraction\x18\t \x01(\t\x12\x15\n\rlistened_from\x18\n \x01(\t\x12\n\n\x02ts\x18\x0b \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spotify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SPOTIFY']._serialized_start=18
  _globals['_SPOTIFY']._serialized_end=223
# @@protoc_insertion_point(module_scope)
